/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },colors: {
        black: "#000",
        gainsboro: "#d9d9d9",
        darkgray: "#9f9f9f",
        gray: {
          "100": "#242424",
          "200": "rgba(0, 0, 0, 0.17)",
        },
        lightsteelblue: "#bfe0ff",
        "color-gray-3": "#898989",
        lightskyblue: "#aed8fe",
        lavender: "#d9ebfb",
        steelblue: {
          "100": "#276aa6",
          "200": "#1960a0",
        },
        "color-white": "#fff",
        "color-primary": "#e89f71",
        "color-gray-1": "#3a3a3a",
        "color-green-accents": "#2ec1ac",
        "color-red-accents": "#e97171",
        "color-gray-4": "#b0b0b0",
        primary: "#b88e2f",
        crimson: "#d42b2b",
        mediumslateblue: "#816dfa",
        linen: "#f9f1e7",
        cornflowerblue: "#51acff",
        aliceblue: "#e7f3ff",
        "color-gray-2": "#616161",
        silver: "#c4c4c4",
        "font-color1": "#666",
        "font-color": "#333",
        lightgray: "#d7d7d7",
      },
      fontFamily: {
        poppins: "Poppins",
        montserrat: "Montserrat",
      },
      borderRadius: {
        mini: "15px",
        "8xs": "5px",
        "3xs": "10px",
        "31xl": "50px",
        smi: "13px",
      },
    },fontSize: {
      base: "16px",
      sm: "14px",
      "5xl": "24px",
      xl: "20px",
      "6xl": "25px",
      "13xl": "32px",
      "29xl": "48px",
      "15xl": "34px",
      xs: "12px",
      "17xl": "36px",
      "4xl": "23px",
      smi: "13px",
      "23xl": "42px",
      lg: "18px",
      "33xl": "52px",
      "21xl": "40px",
    },
  },
  plugins: [],
}
